"""Export a portable inference script and its feature-complete model bundle."""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, PlainTextResponse

from ml.artifacts import load_model_bundle
from ml.van_krevelen import DEFAULT_VK_GROUPS
from routers._utils import get_project_dir, safe_child_path, validate_id
from schemas.base import CamelModel

router = APIRouter(prefix="/api/projects/{project_id}/code-export", tags=["code-export"])


class ExportRequest(CamelModel):
    model_name: str | None = None
    include_comments: bool = True


def _resolve_bundle(project_id: str, model_name: str | None):
    proj_dir = get_project_dir(project_id)
    if model_name:
        name = validate_id(model_name, "model_name")
        path = safe_child_path(proj_dir / "models", f"{name}.joblib")
        download_name = f"{name}.joblib"
    else:
        runs_path = proj_dir / "training_runs.json"
        if not runs_path.exists():
            raise HTTPException(status_code=404, detail="No training runs found")
        with open(runs_path, encoding="utf-8") as f:
            runs = json.load(f)
        if not runs:
            raise HTTPException(status_code=404, detail="No training runs found")
        run_id = runs[-1]["run_id"]
        path = proj_dir / f"bundle_{run_id}.joblib"
        download_name = f"polyml-model-{run_id[:8]}.joblib"
    if not path.exists():
        raise HTTPException(status_code=409, detail="Feature-complete model bundle not found; retrain the model")
    try:
        bundle = load_model_bundle(path)
    except ValueError as exc:
        raise HTTPException(status_code=409, detail=str(exc))
    return path, download_name, bundle


@router.post("/generate")
async def generate_code(project_id: str, req: ExportRequest):
    _, bundle_name, bundle = _resolve_bundle(project_id, req.model_name)
    script = _build_script(bundle.feature_spec, DEFAULT_VK_GROUPS, req.include_comments)
    compile(script, "<polyml-export>", "exec")
    return {
        "script": script,
        "filename": f"polyml-reproduce-{bundle.run_id[:8]}.py",
        "bundle_filename": bundle_name,
    }


@router.get("/download")
async def download_script(project_id: str, model_name: str | None = None):
    _, _, bundle = _resolve_bundle(project_id, model_name)
    script = _build_script(bundle.feature_spec, DEFAULT_VK_GROUPS, True)
    compile(script, "<polyml-export>", "exec")
    return PlainTextResponse(
        script,
        media_type="text/x-python",
        headers={"Content-Disposition": f"attachment; filename=polyml-reproduce-{bundle.run_id[:8]}.py"},
    )


@router.get("/bundle")
async def download_bundle(project_id: str, model_name: str | None = None):
    path, download_name, _ = _resolve_bundle(project_id, model_name)
    return FileResponse(path, filename=download_name, media_type="application/octet-stream")


def _build_script(feature_spec: dict, vk_groups: dict, include_comments: bool) -> str:
    spec_literal = repr(feature_spec)
    vk_literal = repr(vk_groups)
    header = "# Generated by PolyML. Keep this script beside the exported .joblib bundle.\n" if include_comments else ""
    return header + f'''import argparse
import math
import joblib
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors

FEATURE_SPEC = {spec_literal}
VK_GROUPS = {vk_literal}
DESCRIPTORS = dict(Descriptors.descList)
ALLOWED_FUNCTIONS = {{
    "abs": np.abs, "sqrt": np.sqrt, "log": np.log, "log10": np.log10,
    "exp": np.exp, "min": np.minimum, "max": np.maximum, "power": np.power,
}}


def _custom_features(df, smiles_col):
    output = {{}}
    for rule in FEATURE_SPEC.get("customRules", []):
        kind = rule.get("ruleType", rule.get("rule_type", "formula"))
        name = rule.get("name") or "custom"
        expr = rule.get("expression", "")
        params = rule.get("params", {{}})
        if kind == "formula":
            context = {{col: pd.to_numeric(df[col], errors="coerce").to_numpy(float) for col in df.columns}}
            context.update(ALLOWED_FUNCTIONS)
            output[name] = np.asarray(eval(expr, {{"__builtins__": {{}}}}, context), dtype=float)
        elif kind == "interaction":
            a = params.get("column_a", expr.split("*")[0].strip())
            b = params.get("column_b", expr.split("*")[1].strip())
            output[name] = pd.to_numeric(df[a], errors="coerce").to_numpy(float) * pd.to_numeric(df[b], errors="coerce").to_numpy(float)
        elif kind == "bin":
            col = params.get("column", expr)
            edges = params.get("bin_edges")
            if not edges:
                raise ValueError(f"Custom bin feature {{name}} has no persisted edges")
            output[name] = pd.cut(pd.to_numeric(df[col], errors="coerce"), bins=edges, labels=False, include_lowest=True).to_numpy(float)
        elif kind == "substructure":
            patterns = params.get("patterns", [expr])
            patterns = [patterns] if isinstance(patterns, str) else patterns
            compiled = [Chem.MolFromSmarts(pattern) for pattern in patterns]
            values = []
            for smiles in df[smiles_col].astype(str):
                mol = Chem.MolFromSmiles(smiles)
                values.append(sum(len(mol.GetSubstructMatches(pattern)) for pattern in compiled if mol is not None and pattern is not None))
            output[name] = np.asarray(values, dtype=float)
        elif kind == "domain":
            formula = expr.lower()
            if formula == "mark_houwink":
                mw = pd.to_numeric(df[params.get("mw_column", "Mw")], errors="coerce").to_numpy(float)
                output[name] = float(params.get("K", 1.0)) * np.power(mw, float(params.get("a", 0.7)))
            elif formula in {{"fox", "gordon_taylor"}}:
                w1 = pd.to_numeric(df[params.get("w1_column", "w1")], errors="coerce").to_numpy(float)
                tg1 = pd.to_numeric(df[params.get("tg1_column", "Tg1")], errors="coerce").to_numpy(float)
                w2 = pd.to_numeric(df[params.get("w2_column", "w2")], errors="coerce").to_numpy(float)
                tg2 = pd.to_numeric(df[params.get("tg2_column", "Tg2")], errors="coerce").to_numpy(float)
                if formula == "fox":
                    output[name] = 1.0 / (w1 / tg1 + w2 / tg2)
                else:
                    factor = float(params.get("K", 1.0))
                    output[name] = (w1 * tg1 + factor * w2 * tg2) / (w1 + factor * w2)
            else:
                raise ValueError(f"Unsupported domain formula: {{formula}}")
        else:
            raise ValueError(f"Unsupported exported custom feature: {{kind}}")
    return output


def transform(df):
    names = FEATURE_SPEC["featureNames"]
    columns = {{}}
    smiles_col = FEATURE_SPEC.get("smilesColumn")
    mols = [Chem.MolFromSmiles(str(value)) for value in df[smiles_col]] if smiles_col else []

    if FEATURE_SPEC.get("descriptors") and mols:
        for name in names:
            fn = DESCRIPTORS.get(name)
            if fn is not None:
                values = []
                for mol in mols:
                    try:
                        values.append(float(fn(mol)) if mol is not None else np.nan)
                    except Exception:
                        values.append(np.nan)
                columns[name] = np.asarray(values, dtype=float)

    if FEATURE_SPEC.get("vanKrevelen") and mols:
        compiled = {{key: Chem.MolFromSmarts(info["smarts"]) for key, info in VK_GROUPS.items()}}
        for key, pattern in compiled.items():
            counts = np.asarray([len(mol.GetSubstructMatches(pattern)) if mol is not None and pattern is not None else 0 for mol in mols], dtype=float)
            columns[f"vk_count_{{key}}"] = counts
            columns[f"vk_Yg_{{key}}"] = counts * float(VK_GROUPS[key]["Yg"])
        columns["vk_M0"] = np.asarray([Descriptors.MolWt(mol) if mol is not None else 0.0 for mol in mols])
        columns["vk_Yg_total"] = sum((columns[f"vk_Yg_{{key}}"] for key in compiled), np.zeros(len(df)))

    for name in FEATURE_SPEC.get("numericColumns", []):
        columns[name] = pd.to_numeric(df[name], errors="coerce").to_numpy(float) if name in df else np.full(len(df), np.nan)
    columns.update(_custom_features(df, smiles_col))

    X = np.full((len(df), len(names)), np.nan, dtype=float)
    for index, name in enumerate(names):
        if name in columns:
            X[:, index] = columns[name]
    return X


def main():
    parser = argparse.ArgumentParser(description="Run a PolyML model bundle")
    parser.add_argument("--bundle", default="model_bundle.joblib")
    parser.add_argument("--input", default="data.csv")
    parser.add_argument("--output", default="predictions.csv")
    args = parser.parse_args()
    payload = joblib.load(args.bundle)
    if payload.get("artifactType") != "PolyMLModelBundle" or payload.get("schemaVersion") != 2:
        raise ValueError("Unsupported PolyML model bundle")
    data = pd.read_csv(args.input)
    X = transform(data)
    predictions = np.asarray(payload["pipeline"].predict(X)).reshape(-1)
    result = data.copy()
    result[payload.get("targetName", "prediction") + "_predicted"] = predictions
    result.to_csv(args.output, index=False)
    print(f"Wrote {{len(result)}} predictions to {{args.output}}")


if __name__ == "__main__":
    main()
'''
